const initialBooks = [
    { title: "1984", author: "George Orwell", pages: "328", hasBeenRead: "true" },
    { title: "To Kill a Mockingbird", author: "Harper Lee", pages: "281", hasBeenRead: "false" },
    { title: "The Great Gatsby", author: "F. Scott Fitzgerald", pages: "180", hasBeenRead: "true" },
    { title: "Moby Dick", author: "Herman Melville", pages: "635", hasBeenRead: "false" },
    { title: "Pride and Prejudice", author: "Jane Austen", pages: "279", hasBeenRead: "true" },
    { title: "The Catcher in the Rye", author: "J.D. Salinger", pages: "214", hasBeenRead: "false" },
    { title: "The Hobbit", author: "J.R.R. Tolkien", pages: "310", hasBeenRead: "true" },
    { title: "Fahrenheit 451", author: "Ray Bradbury", pages: "194", hasBeenRead: "true" },
    { title: "Brave New World", author: "Aldous Huxley", pages: "268", hasBeenRead: "false" },
    { title: "The Lord of the Rings", author: "J.R.R. Tolkien", pages: "1178", hasBeenRead: "true" },
    { title: "Dune", author: "Frank Herbert", pages: "412", hasBeenRead: "false" },
    { title: "Neuromancer", author: "William Gibson", pages: "271", hasBeenRead: "false" },
    { title: "The Last Wish", author: "Andrzej Sapkowski", pages: "288", hasBeenRead: "false" },
    { title: "Metro 2033", author: "Dmitry Glukhovsky", pages: "416", hasBeenRead: "false" },
    { title: "Do Androids Dream of Electric Sheep?", author: "Philip K. Dick", pages: "210", hasBeenRead: "false" },
    { title: "At the Mountains of Madness", author: "H. P. Lovecraft", pages: "160", hasBeenRead: "false" },
    { title: "Dracula", author: "Bram Stoker", pages: "418", hasBeenRead: "false" },
    { title: "Frankenstein", author: "Mary Shelley", pages: "280", hasBeenRead: "false" },
    { title: "Alice's Adventures in Wonderland", author: "Lewis Carroll", pages: "201", hasBeenRead: "false" },
    { title: "The Divine Comedy (Inferno)", author: "Dante Alighieri", pages: "448", hasBeenRead: "false" },
    { title: "The Road", author: "Cormac McCarthy", pages: "287", hasBeenRead: "false" },
    { title: "American Gods", author: "Neil Gaiman", pages: "465", hasBeenRead: "false" },
    { title: "The Call of Cthulhu and Other Weird Stories", author: "H. P. Lovecraft", pages: "320", hasBeenRead: "false" },
    { title: "Ringworld", author: "Larry Niven", pages: "384", hasBeenRead: "false" },
    { title: "The Iliad", author: "Homer", pages: "704", hasBeenRead: "false" },
    { title: "The Odyssey", author: "Homer", pages: "541", hasBeenRead: "false" },
    { title: "Blood Meridian", author: "Cormac McCarthy", pages: "336", hasBeenRead: "false" },
    { title: "The Silence of the Lambs", author: "Thomas Harris", pages: "352", hasBeenRead: "false" },
    { title: "Solaris", author: "Stanisław Lem", pages: "224", hasBeenRead: "false" },
    { title: "Sword of Destiny", author: "Andrzej Sapkowski", pages: "384", hasBeenRead: "false" }
];